### PR TITLE
Feature/record expiry

### PR DESCRIPTION
**Pull request by arnkthr**
Added configuration to allow the connector to send records which will expire from redis at a globally configured time.

### CODE REVIEW

**Comment by jcustenborder** [comment]
@arnkthr Can you help me understand why this change is needed?

**Comment by arnkthr** [comment]
> @arnkthr Can you help me understand why this change is needed?

Hi @jcustenborder, sorry, the change aims to provide the functionality mentioned in this issue
https://github.com/jcustenborder/kafka-connect-redis/issues/26

**Comment by cch0** [comment]
Are we waiting on anything before we can approve and merge this other than resolving the merge conflict?

**Comment by lmeadors** [comment]
Is there a reason that this isn't being merged? 

Setting TTL on cache entries so they expire eventually seems like a complete no-brainer feature to add, but this has been sitting here for over 18 months.

**Comment by jcustenborder** [comment]
There is a 2.0 version of the connector which has this functionality. It's been in the works for a while. This also required some refactoring to support sentinel and cluster.

**Comment by lmeadors** [comment]
A V2 of this is great news! Two questions:

- what is the ETA on that?
- what can I do to help accelerate that? :)

**Pull request closed without merging**
